version : "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: test_app_mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password